server:
  port: 8001  # 服务端口号

spring:
  application:
    name: tangba-system  # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://ch-server-mysql.mysql.database.azure.com:3306/contracts?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: everyone
    password: 20192019
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yixin.cloud.pojo   # 所有实体类别名类所在包


